@extends('marketing.layout')

@section('title', $industry['title'])
@section('meta_description', $industry['intro'])

@section('content')
    <section class="industry-page-hero"><div class="shell industry-hero-grid"><div>
        <p class="industry-kicker">CraftSalesPOS for {{ $industry['name'] }}</p>
        <h1>{{ $industry['title'] }}.</h1><p class="industry-lead">{{ $industry['intro'] }}</p>
        <div class="industry-actions"><a class="button" href="{{ route('business.getRegister') }}">Get started <span>→</span></a><a class="industry-text-link" href="{{ route('marketing.plans') }}">View plans</a></div>
    </div><figure class="industry-hero-image"><img src="{{ asset('images/landing/' . $industry['image']) }}" alt="{{ $industry['name'] }} using CraftSalesPOS" /></figure></div></section>
    <section class="shell industry-section"><div class="industry-section-heading"><span>Built around the day-to-day</span><h2>Less admin. More time for customers.</h2><p>A practical point-of-sale system gives your team a consistent way to sell, track stock and review performance.</p></div>
        <div class="industry-columns"><article class="industry-panel"><h3>Common operational pressures</h3><ul>@foreach($industry['challenges'] as $challenge)<li>{{ $challenge }}</li>@endforeach</ul></article><article class="industry-panel accent"><h3>What CraftSalesPOS brings together</h3><ul>@foreach($industry['features'] as $feature)<li>{{ $feature }}</li>@endforeach</ul></article></div>
    </section>
    <section class="industry-proof"><div class="shell proof-grid"><div><strong>One clear view</strong><span>See sales and inventory without jumping between tools.</span></div><div><strong>A steadier counter</strong><span>Make checkout simple for staff and customers alike.</span></div><div><strong>Ready to grow</strong><span>Add people, products and locations as your business evolves.</span></div></div></section>
    <section class="shell industry-cta"><div><span>Ready when you are</span><h2>Run your {{ strtolower($industry['name']) }} with more clarity.</h2></div><a class="button light" href="{{ route('business.getRegister') }}">Create your workspace <span>→</span></a></section>
@endsection

@push('styles')
<style>
.industry-page-hero{padding:82px 0 70px;background:radial-gradient(circle at 78% 15%,#c9f1d9 0,transparent 26rem),linear-gradient(135deg,#effaf3,#fff)}.industry-hero-grid{display:grid;grid-template-columns:1.04fr .96fr;gap:64px;align-items:center}.industry-kicker,.industry-section-heading>span,.industry-cta span{color:#197247;text-transform:uppercase;letter-spacing:.1em;font-size:.76rem;font-weight:800}.industry-page-hero h1{margin:12px 0 18px;max-width:650px;font-size:clamp(2.45rem,5vw,4.35rem);line-height:1.03;letter-spacing:-.055em}.industry-lead{max-width:570px;color:#56647b;font-size:1.14rem;line-height:1.75}.industry-actions{display:flex;gap:22px;align-items:center;margin-top:30px}.button{display:inline-flex;align-items:center;gap:16px;padding:13px 19px;border-radius:10px;background:#176440;color:#fff;font-weight:800}.button span{font-size:1.25rem}.industry-text-link{font-weight:750;color:#176440}.industry-hero-image{margin:0;border-radius:25px;overflow:hidden;box-shadow:0 30px 60px -28px #173f2b}.industry-hero-image img{display:block;width:100%;aspect-ratio:1.12;object-fit:cover}.industry-section{padding:92px 0}.industry-section-heading{text-align:center;max-width:680px;margin:0 auto 42px}.industry-section-heading h2{font-size:clamp(2rem,4vw,3rem);letter-spacing:-.045em;margin:11px 0}.industry-section-heading p{color:#66738a;line-height:1.7}.industry-columns{display:grid;grid-template-columns:1fr 1fr;gap:22px}.industry-panel{padding:30px;border:1px solid #dfe8e2;border-radius:18px;background:#fff}.industry-panel.accent{background:#f0fbf4;border-color:#cdebd8}.industry-panel h3{margin:0 0 19px;font-size:1.08rem}.industry-panel ul{margin:0;padding:0;list-style:none}.industry-panel li{padding:12px 0 12px 26px;border-top:1px solid #e3ebe6;position:relative;color:#526177}.industry-panel li:before{content:'✓';position:absolute;left:0;color:#1f8051;font-weight:900}.industry-proof{background:#143f2a;color:#fff;padding:38px 0}.proof-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:35px}.proof-grid strong{display:block;font-size:1.12rem;margin-bottom:9px}.proof-grid span{color:#b8dfc6;line-height:1.55}.industry-cta{margin:86px auto;padding:46px 52px;border-radius:22px;display:flex;align-items:center;justify-content:space-between;gap:25px;background:#1b7048;color:#fff}.industry-cta span{color:#bce7cb}.industry-cta h2{margin:8px 0 0;max-width:600px;font-size:clamp(1.7rem,3vw,2.45rem);letter-spacing:-.04em}.button.light{background:#fff;color:#176440;white-space:nowrap}@media(max-width:760px){.industry-page-hero{padding:56px 0}.industry-hero-grid,.industry-columns,.proof-grid{grid-template-columns:1fr}.industry-hero-grid{gap:34px}.industry-section{padding:62px 0}.industry-cta{margin:56px auto;padding:34px 27px;align-items:flex-start;flex-direction:column}.industry-hero-image{order:-1}}
</style>
@endpush
